# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/Gitbook-Plugin-Json-Schema
  docker:
    - image: circleci/node:8.9.4
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

      - run: yarn install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
        root: .
        paths:
            - .
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
        at: ~/WeedApp      
      - run:
        name: "Lint"
        command: yarn lint
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
        at: ~/WeedApp     
      - run:
        name: "Test"
        command: yarn test -- --ci
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
              - build
      - test:
          requires:
              - build